version: '3'
services:
  php:
    build: php
    volumes:
      - ../src:/var/www/html
  nginx:
    build: nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ../src:/var/www/html
